on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "testing githup actions"
        run: pwd

      - uses: actions/checkout@v3
      - name: "login to docker hub"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWOED}}
